### ISSUE TITLE
bake bakePreview does not work?

### ISSUE THREAD

**Issue by supsup** [melix/blog#7]
------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

----
> Task :bakePreview FAILED
Starting server. Browse to http://localhost:8080

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bakePreview'.
> org/eclipse/jetty/server/nio/SelectChannelConnector

w/ --verbose:

```
org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/nio/SelectChannelConnector
        at org.jbake.launcher.JettyServer.run(JettyServer.java:30)
        at org.jbake.launcher.JettyServer$run.call(Unknown Source)
        at org.jbake.launcher.JettyServer$run.call(Unknown Source)
        at org.jbake.gradle.impl.JettyServerProxyImpl.run(JettyServerProxyImpl.groovy:28)
        at org.jbake.gradle.JettyServerProxy$run$0.call(Unknown Source)
        at org.jbake.gradle.JBakeServeTask.serve(JBakeServeTask.groovy:52
```

**Comment by supsup** [comment]
Just context I was reviewing
https://github.com/jbake-org/jbake-gradle-plugin
 and it mentioned this as a good example to review use.

**Comment by supsup** [comment]
I think this is because I am using Java 8...saw the Spring 5+ but missed the Java 7 Req
